version: "3.8"

services:

    postgres:
        image: postgres:latest
        container_name: postgres
        environment:
            - POSTGRES_USER=user01
            - POSTGRES_PASSWORD=user01
        volumes:
            - postgres-data:/var/lib/postgresql/data
        ports:
            - 5432:5432
        restart: unless-stopped

volumes:
    postgres-data:
        name: postgres-data